import Header from "@/components/Common/Header/Header";
import "./globals.css";
import { Inter, Montserrat, Unbounded } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="px-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
