import Footer from "@/components/Common/Footer";
import "./globals.css";
import Header from "@/components/Common/Header/Header";
import clsx from "clsx";
import { Inter, Montserrat, Unbounded } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(["bg-body-light"], montserrat.className)}>
        <div className="flex h-full flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
